# This variable is the crux of the workflow.
# The workspace name will be generated by the name of the object.
# See the terraform.auto.tfvars file for some examples.
#
# The optional attributes experiment is enabled in the backend.tf file.
variable "workspaces" {
  type = map(object({
    terraform_version = optional(string)
    queue_all_runs    = optional(bool)
    execution_mode    = optional(string)
    allow_destroy_plan = optional(bool)
    working_directory = optional(string)
    file_triggers_enabled = optional(bool)
    trigger_prefixes = optional(list(string))
    vcs_repo          = optional(object({
      identifier = string
      oauth_token_id = string
      branch = optional(string)
      submodule_ingress = optional(bool)
    }))
  }))

  description = "This map of objects allows for simplified creation of a workspace."
}

variable "organization_name" {
  type        = string
  description = "TFC Organization name"
}

variable "organization_email" {
  type        = string
  description = "TFC Organization email"
}

# Because this configuration will run in the workspace itself
# this variable expects that an environment variable named
# TF_VAR_AWS_SECRET_ACCESS_KEY exists in the administrative workspace.
variable "AWS_SECRET_ACCESS_KEY" {
  type        = string
  description = "AWS Secret Key"
}

# Because this configuration will run in the workspace itself
# this variable expects that an environment variable named
# TF_VAR_AWS_ACCESS_KEY_ID exists in the administrative workspace.
variable "AWS_ACCESS_KEY_ID" {
  type        = string
  description = "AWS Access Key ID"
}